# Generated by Django 4.2.1 on 2023-05-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human Readable Name of this Image", max_length=256
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="\nName of the image (without the tag).\n\nEg. pangeo/pangeo-notebook, quay.io/your-org/your-image\n",
                        max_length=1024,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="\nTag of the image to pull from.\n\nEg 2022-01-05, kljhfahlfalksjdf32434. Recommend against using 'latest' tag",
                        max_length=1024,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_default", models.BooleanField(verbose_name="Default image?")),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configurator.image",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configurator.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ManyToManyField(
                through="configurator.ProfileImage", to="configurator.image"
            ),
        ),
        migrations.AddConstraint(
            model_name="profileimage",
            constraint=models.UniqueConstraint(
                fields=("profile", "image"), name="unique_image_per_profile"
            ),
        ),
    ]
