# Generated by Django 4.2.1 on 2023-05-23 06:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configurator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="name",
            new_name="display_name",
        ),
    ]
