# Generated by Django 4.2.1 on 2023-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="description",
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(
                help_text="Human Readable Name of this Image", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="spec",
            field=models.CharField(
                help_text="Spec to pull the image. eg. quay.io/username/image-name:tag or pangeo/pangeo-notebook:tag. Tag is required",
                max_length=1024,
            ),
        ),
    ]
