# Generated by Django 4.2.1 on 2023-05-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurator", "0002_rename_name_profile_display_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="profileimage",
            name="unique_image_per_profile",
        ),
        migrations.AddConstraint(
            model_name="profileimage",
            constraint=models.UniqueConstraint(
                fields=("profile", "image"),
                name="unique_image_per_profile",
                violation_error_message="An image can be present only once in a profile",
            ),
        ),
    ]
